export const buttons: string[] = [
	"Home",
	"Customer",
	"Supplier Management",
	"Sales Agent",
	"Inventory Officer",
	"Account",
	"Inventory",
	"Order Generator",
	"Role Management",
];

export const containerType = [
	"20' 1 TRIPPER",
	"20' CW",
	"20' HC 1 TRIPPER",
	"20' STD DD",
	"20' WWT",
	"40' 1 TRIPPER",
	"40' CW",
	"40' HC 1 TRIPPER",
	"40' HC CW",
	"40' HC DD",
	"40' HC 4D",
	"40' HC OS",
	"40' HC REEFER (NEW)",
	"40' HC REEFER (WORKING)",
	"40' HC WWT",
	"40' STD 1 TRIPPER",
	"40' WWT",
	"45' HC",
	"20' OS",
	"20' RFR (NEW)",
	"20' RFR (NW)",
	"20' RFR (WORKING)",
	"20 RFR (AS IS)",
	"20' HC DD",
	"20' HC",
	"20 DUO",
	"ANY",
	"40' HC RFR (NW)",
	"40' DD",
	"40' HC AS IS",
	"20' STD AS IS",
	"40' STD IICL",
	"40' HC IICL",
	"53' HC CW",
	"53 HC New",
	"20' STD IICL",
];
