import { InventoryTypes, Payment, StatesType, TableDataProps } from "./props";

export type PinObjectProps = {
	name: string;
	pin: string;
};

export const pinObject: PinObjectProps[] = [
	{ name: "pin1", pin: "" },
	{ name: "pin2", pin: "" },
	{ name: "pin3", pin: "" },
	{ name: "pin4", pin: "" },
];

type CustomerTypeProps = {
	title: string;
	description: string;
	route: string;
};

export const CustomerType: CustomerTypeProps[] = [
	{
		title: "Shipping",
		description: "Shipping container business",
		route: "shipping",
	},
	{
		title: "Trucking",
		description: "Container trucking business",
		route: "trucking",
	},
];

type InventoryType = {
	title: string;
	location: string;
	quantity: string;
	price: string;
};

export const InventoryObject: InventoryType[] = [
	{
		location: "025145 | Chicago, USA | Depot",
		price: "$ 1,250",
		quantity: "12 PCS",
		title: "20 STD - CW",
	},
	{
		location: "025145 | Chicago, USA | Depot",
		price: "$ 1,250",
		quantity: "12 PCS",
		title: "40 HC - CW",
	},
	{
		location: "025145 | Chicago, USA | Depot",
		price: "$ 1,250",
		quantity: "12 PCS",
		title: "20 STD - OT",
	},
];

type SupplierManagementTypes = {
	id: number;
	title: string;
	subtitle: string;
	price: string;
	quantity: string;
};

export const SupplierManagementData: SupplierManagementTypes[] = [
	{
		id: 1,
		title: "20 STD - CW",
		subtitle: "025145 | Chicago, USA | Depot",
		price: "$ 1,250",
		quantity: "12 PCS",
	},
	{
		id: 2,
		title: "40 HC - CW",
		subtitle: "025145 | Chicago, USA | Depot",
		price: "$ 1,250",
		quantity: "12 PCS",
	},
	{
		id: 3,
		title: "20 STD - OT",
		subtitle: "025145 | Chicago, USA | Depot",
		price: "$ 1,250",
		quantity: "12 PCS",
	},
];

export const InventoryTableData: TableDataProps[] = [
	{
		id: 1,
		columnTitle: "Product Name",
		tableData: ["20 STD - CW", "40 HC - CW", "20 STD - OT"],
	},
	{
		id: 2,
		columnTitle: "City",
		tableData: ["Chicago", "Chicago", "Chicago"],
	},
	{
		id: 3,
		columnTitle: "State",
		tableData: ["USA", "USA", "USA"],
	},
	{
		id: 4,
		columnTitle: "Quantity",
		tableData: ["12 PCS", "12 PCS", "12 PCS"],
	},
	{
		id: 5,
		columnTitle: "Depot",
		tableData: ["Depot", "Depot", "Depot"],
	},
	{
		id: 6,
		columnTitle: "Price",
		tableData: ["$ 1,250", "$ 1,250", "$ 1,250"],
	},
];

export const SupplierTableData: TableDataProps[] = [
	{
		id: 1,
		columnTitle: "Supplier",
		tableData: [
			"East Pacific Container",
			"North Pacific Container",
			"North Atlantic",
		],
	},
	{
		id: 2,
		columnTitle: "Location",
		tableData: ["Chicago, USA", "New York, USA", "California, USA"],
	},
	{
		id: 3,
		columnTitle: "Abcde",
		tableData: null,
	},
	{
		id: 4,
		columnTitle: "Contact",
		tableData: ["09154814993", "09154814993", "09154814993"],
	},
];

export type TableTypes<Header, Body> = {
	tableHeader: Header[];
	tableBody: Body[];
};

export const states: StatesType = {
	USA: [
		"Ohio",
		"New Mexico",
		"Virginia",
		"Texas",
		"California",
		"Alaska",
		"Georgia",
		"Illinois",
		"Colorado",
		"Maryland",
		"Louisiana",
		"Puerto Rico",
		"Washington",
		"Alabama",
		"Idaho",
		"Massachusetts",
		"Connecticut",
		"New York",
		"Florida",
		"North Carolina",
		"Arizona",
		"South Carolina",
		"Tennessee",
		"Iowa",
		"Michigan",
		"Nevada",
		"Oregon",
		"Indiana",
		"Mississippi",
		"New Jersey",
		"Missouri",
		"Kansas",
		"Kentucky",
		"Nebraska",
		"Arkansas",
		"Wisconsin",
		"Minnesota",
		"Hawaii",
		"Oklahoma",
		"Rhode Island",
		"Utah",
		"District of Columbia",
		"South Dakota",
	],
	Canada: [
		"British Columbia",
		"Newfoundland",
		"Ontario",
		"Alberta",
		"Quebec",
		"Nova Scotia",
		"Saskatchewan",
		"New Brunswick",
		"Manitoba",
	],
};

// CITY DUPLICATE - Illinois and Colorado has same city called Aurora
export const uniqueCities = [
	// Canada
	"Abbotsford",
	"Kelowna",
	"Vancouver",
	"Victoria",
	"Barrie",
	"Hamilton",
	"Kingston",
	"Kitchener",
	"London",
	"Oshawa",
	"St Catharines-Niagara",
	"Sudbury",
	"Thunder Bay",
	"Toronto",
	"Windsor",
	"Calgary",
	"Edmonton",
	"Chicoutimi",
	"Montréal",
	"Quebéc",
	"Sherbrooke",
	"Trois-Rivières",
	"Halifax",
	"Sydney",
	"Regina",
	"Saskatoon",
	"Saint John",
	"St John's",
	"Winnipeg",

	// USA
	"Akron",
	"Cincinnati",
	"Cleveland",
	"Columbus",
	"Toledo",
	"Albuquerque",
	"Santa Teresa",
	"Alexandria",
	"Arlington",
	"Chesapeake",
	"Newport News",
	"Norfolk",
	"Richmond",
	"Virginia Beach",
	"Amarillo",
	"Arlington",
	"Austin",
	"Brownsville",
	"Corpus Christi",
	"Dallas",
	"Denton",
	"El Paso",
	"Fort Worth",
	"Frisco",
	"Garland",
	"Grand Prairie",
	"Haslet",
	"Houston",
	"Irving",
	"Killeen",
	"Laredo",
	"Lubbock",
	"McAllen",
	"McKinney",
	"Mesquite",
	"Pasadena",
	"Plano",
	"San Antonio",
	"Anaheim",
	"Bakersfield",
	"Chula Vista",
	"Corona",
	"Elk Grove",
	"Escondido",
	"Fontana",
	"Fremont",
	"Fresno",
	"Fullerton",
	"Garden Grove",
	"Glendale",
	"Hayward",
	"Huntington Beach",
	"Irvine",
	"Lancaster",
	"Los Angeles/Long Beach",
	"Modesto",
	"Moreno Valley",
	"Oakland",
	"Oceanside",
	"Ontario",
	"Oxnard",
	"Palmdale",
	"Pomona",
	"Rancho Cucamonga",
	"Riverside",
	"Roseville",
	"Sacramento",
	"Salinas",
	"San Bernardino",
	"San Diego",
	"San Francisco",
	"San Jose",
	"Santa Ana",
	"Santa Clarita",
	"Santa Rosa",
	"Stockton",
	"Sunnyvale",
	"Torrance",
	"Visalia",
	"Anchorage",
	"Atlanta",
	"Augusta",
	"Columbus",
	"Savannah",
	"Aurora",
	"Chicago",
	"Joliet",
	"Naperville",
	"Rockford",
	"Aurora",
	"Colorado Springs",
	"Denver",
	"Fort Collins",
	"Lakewood",
	"Thornton",
	"Baltimore",
	"Baton Rouge",
	"New Orleans",
	"Shreveport",
	"Bayamon",
	"San Juan",
	"Bellevue",
	"Kent",
	"Seatle",
	"Spokane",
	"Tacoma",
	"Vancouver",
	"Birmingham",
	"Huntsville",
	"Mobile",
	"Montgomery",
	"Boise",
	"Boston",
	"Springfield",
	"Worcester",
	"Bridgeport",
	"Buffalo",
	"New York City",
	"Rochester",
	"Syracuse",
	"Yonkers",
	"Cape Coral",
	"Fort Lauderdale",
	"Hialeah",
	"Hollywood",
	"Jacksonville",
	"Miami",
	"Orlando",
	"Pembroke Pines",
	"Port St. Lucie",
	"St. Petersburg",
	"Tallahassee",
	"Tampa",
	"Cary",
	"Charlotte",
	"Durham",
	"Fayetteville",
	"Greensboro",
	"Wilmington",
	"Raleigh",
	"Winston-Salem",
	"Chandler",
	"Gilbert",
	"Glendale",
	"Mesa",
	"Peoria",
	"Phoenix",
	"Scottsdale",
	"Surprise",
	"Tempe",
	"Tucson",
	"Charleston",
	"Greer",
	"Chattanooga",
	"Clarksville",
	"Knoxville",
	"Memphis",
	"Murfreesboro",
	"Nashville",
	"Des Moines",
	"Detroit",
	"Grand Rapids",
	"Enterprise",
	"Henderson",
	"Las Vegas",
	"North Las Vegas",
	"Paradise",
	"Reno",
	"Spring Valley",
	"Sunrise Manor",
	"Eugene",
	"Portland",
	"Salem",
	"Indianapolis",
	"Fort Wayne",
	"Jackson",
	"Jersey City",
	"Township",
	"Newark",
	"Paterson",
	"Kansas City",
	"Springfield",
	"St. Louis",
	"Kansas City",
	"Overland Park",
	"Wichita",
	"Lexington",
	"Louisville",
	"Lincoln",
	"Omaha",
	"Little Rock",
	"Milwaukee",
	"Madison",
	"St. Paul",
	"Minneapolis",
	"Honolulu",
	"Oklahoma City",
	"Tulsa",
	"Providence",
	"Salt Lake City",
	"Washington",
	"Sioux Falls",
];

export const cities = {
	// CANADA
	"British Columbia": ["Abbotsford", "Kelowna", "Vancouver", "Victoria"],
	Ontario: [
		"Barrie",
		"Hamilton",
		"Kingston",
		"Kitchener",
		"London",
		"Oshawa",
		"St Catharines-Niagara",
		"Sudbury",
		"Thunder Bay",
		"Toronto",
		"Windsor",
	],
	Alberta: ["Calgary", "Edmonton"],
	Quebec: ["Chicoutimi", "Montréal", "Quebéc", "Sherbrooke", "Trois-Rivières"],
	"Nova Scotia": ["Halifax", "Sydney"],
	Saskatchewan: ["Regina", "Saskatoon"],
	"New Brunswick": ["Saint John"],
	Newfoundland: ["St John's"],
	Manitoba: ["Winnipeg"],

	// USA
	Ohio: ["Akron", "Cincinnati", "Cleveland", "Columbus", "Toledo"],
	"New Mexico": ["Albuquerque", "Santa Teresa"],
	Virginia: [
		"Alexandria",
		"Arlington",
		"Chesapeake",
		"Newport News",
		"Norfolk",
		"Richmond",
		"Virginia Beach",
	],
	Texas: [
		"Amarillo",
		"Arlington",
		"Austin",
		"Brownsville",
		"Corpus Christi",
		"Dallas",
		"Denton",
		"El Paso",
		"Fort Worth",
		"Frisco",
		"Garland",
		"Grand Prairie",
		"Haslet",
		"Houston",
		"Irving",
		"Killeen",
		"Laredo",
		"Lubbock",
		"McAllen",
		"McKinney",
		"Mesquite",
		"Pasadena",
		"Plano",
		"San Antonio",
	],
	California: [
		"Anaheim",
		"Bakersfield",
		"Chula Vista",
		"Corona",
		"Elk Grove",
		"Escondido",
		"Fontana",
		"Fremont",
		"Fresno",
		"Fullerton",
		"Garden Grove",
		"Glendale",
		"Hayward",
		"Huntington Beach",
		"Irvine",
		"Lancaster",
		"Los Angeles/Long Beach",
		"Modesto",
		"Moreno Valley",
		"Oakland",
		"Oceanside",
		"Ontario",
		"Oxnard",
		"Palmdale",
		"Pomona",
		"Rancho Cucamonga",
		"Riverside",
		"Roseville",
		"Sacramento",
		"Salinas",
		"San Bernardino",
		"San Diego",
		"San Francisco",
		"San Jose",
		"Santa Ana",
		"Santa Clarita",
		"Santa Rosa",
		"Stockton",
		"Sunnyvale",
		"Torrance",
		"Visalia",
	],
	Alaska: ["Anchorage"],
	Georgia: ["Atlanta", "Augusta", "Columbus", "Savannah"],
	Illinois: ["Aurora", "Chicago", "Joliet", "Naperville", "Rockford"],
	Colorado: [
		"Aurora",
		"Colorado Springs",
		"Denver",
		"Fort Collins",
		"Lakewood",
		"Thornton",
	],
	Maryland: ["Baltimore"],
	Louisiana: ["Baton Rouge", "New Orleans", "Shreveport"],
	"Puerto Rico": ["Bayamon", "San Juan"],
	Washington: ["Bellevue", "Kent", "Seatle", "Spokane", "Tacoma", "Vancouver"],
	Alabama: ["Birmingham", "Huntsville", "Mobile", "Montgomery"],
	Idaho: ["Boise"],
	Massachusetts: ["Boston", "Springfield", "Worcester"],
	Connecticut: ["Bridgeport"],
	"New York": ["Buffalo", "New York City", "Rochester", "Syracuse", "Yonkers"],
	Florida: [
		"Cape Coral",
		"Fort Lauderdale",
		"Hialeah",
		"Hollywood",
		"Jacksonville",
		"Miami",
		"Orlando",
		"Pembroke Pines",
		"Port St. Lucie",
		"St. Petersburg",
		"Tallahassee",
		"Tampa",
	],
	"North Carolina": [
		"Cary",
		"Charlotte",
		"Durham",
		"Fayetteville",
		"Greensboro",
		"Wilmington",
		"Raleigh",
		"Winston-Salem",
	],
	Arizona: [
		"Chandler",
		"Gilbert",
		"Glendale",
		"Mesa",
		"Peoria",
		"Phoenix",
		"Scottsdale",
		"Surprise",
		"Tempe",
		"Tucson",
	],
	"South Carolina": ["Charleston", "Greer"],
	Tennessee: [
		"Chattanooga",
		"Clarksville",
		"Knoxville",
		"Memphis",
		"Murfreesboro",
		"Nashville",
	],
	Iowa: ["Des Moines"],
	Michigan: ["Detroit", "Grand Rapids"],
	Nevada: [
		"Enterprise",
		"Henderson",
		"Las Vegas",
		"North Las Vegas",
		"Paradise",
		"Reno",
		"Spring Valley",
		"Sunrise Manor",
	],
	Oregon: ["Eugene", "Portland", "Salem"],
	Indiana: ["Indianapolis", "Fort Wayne"],
	Mississippi: ["Jackson"],
	"New Jersey": ["Jersey City", "Township", "Newark", "Paterson"],
	Missouri: ["Kansas City", "Springfield", "St. Louis"],
	Kansas: ["Kansas City", "Overland Park", "Wichita"],
	Kentucky: ["Lexington", "Louisville"],
	Nebraska: ["Lincoln", "Omaha"],
	Arkansas: ["Little Rock"],
	Wisconsin: ["Milwaukee", "Madison"],
	Minnesota: ["St. Paul", "Minneapolis"],
	Hawaii: ["Honolulu"],
	Oklahoma: ["Oklahoma City", "Tulsa"],
	"Rhode Island": ["Providence"],
	Utah: ["Salt Lake City"],
	"District of Columbia": ["Washington"],
	"South Dakota": ["Sioux Falls"],
};

export const payments: Payment[] = [
	{
		abcde: "Sample Abcde",
		contact: "Sample Contact",
		location: "Sample Location",
		supplier: "Sample Supplier",
	},
	{
		abcde: "Sample Abcde 1",
		contact: "Sample Contact 1",
		location: "Sample Location 1",
		supplier: "Sample Supplier 1",
	},
	{
		abcde: "Sample Abcde 2",
		contact: "Sample Contact 2",
		location: "Sample Location 2",
		supplier: "Sample Supplier 2",
	},
	{
		abcde: "Sample Abcde 3",
		contact: "Sample Contact 3",
		location: "Sample Location 3",
		supplier: "Sample Supplier 3",
	},
	{
		abcde: "Sample Abcde 4",
		contact: "Sample Contact 4",
		location: "Sample Location 4",
		supplier: "Sample Supplier 4",
	},
	{
		abcde: "Sample Abcde 5",
		contact: "Sample Contact 5",
		location: "Sample Location 5",
		supplier: "Sample Supplier 5",
	},
	{
		abcde: "Sample Abcde 6",
		contact: "Sample Contact 6",
		location: "Sample Location 6",
		supplier: "Sample Supplier 6",
	},
	{
		abcde: "Sample Abcde 7",
		contact: "Sample Contact 7",
		location: "Sample Location 7",
		supplier: "Sample Supplier 7",
	},
	{
		abcde: "Sample Abcde 8",
		contact: "Sample Contact 8",
		location: "Sample Location 8",
		supplier: "Sample Supplier 8",
	},
	{
		abcde: "Sample Abcde 9",
		contact: "Sample Contact 9",
		location: "Sample Location 9",
		supplier: "Sample Supplier 9",
	},
	{
		abcde: "Sample Abcde 10",
		contact: "Sample Contact 10",
		location: "Sample Location 10",
		supplier: "Sample Supplier 10",
	},
	{
		abcde: "Sample Abcde 11",
		contact: "Sample Contact 11",
		location: "Sample Location 11",
		supplier: "Sample Supplier 11",
	},
	{
		abcde: "Sample Abcde 12",
		contact: "Sample Contact 12",
		location: "Sample Location 12",
		supplier: "Sample Supplier 12",
	},
	{
		abcde: "Sample Abcde 13",
		contact: "Sample Contact 13",
		location: "Sample Location 13",
		supplier: "Sample Supplier 13",
	},
	{
		abcde: "Sample Abcde 14",
		contact: "Sample Contact 14",
		location: "Sample Location 14",
		supplier: "Sample Supplier 14",
	},
	{
		abcde: "Sample Abcde 15",
		contact: "Sample Contact 15",
		location: "Sample Location 15",
		supplier: "Sample Supplier 15",
	},
	{
		abcde: "Sample Abcde 16",
		contact: "Sample Contact 16",
		location: "Sample Location 16",
		supplier: "Sample Supplier 16",
	},
	{
		abcde: "Sample Abcde 17",
		contact: "Sample Contact 17",
		location: "Sample Location 17",
		supplier: "Sample Supplier 17",
	},
	{
		abcde: "Sample Abcde 18",
		contact: "Sample Contact 18",
		location: "Sample Location 18",
		supplier: "Sample Supplier 18",
	},
	{
		abcde: "Sample Abcde 19",
		contact: "Sample Contact 19",
		location: "Sample Location 19",
		supplier: "Sample Supplier 19",
	},
	{
		abcde: "Sample Abcde 20",
		contact: "Sample Contact 20",
		location: "Sample Location 20",
		supplier: "Sample Supplier 20",
	},
	{
		abcde: "Sample Abcde 21",
		contact: "Sample Contact 21",
		location: "Sample Location 21",
		supplier: "Sample Supplier 21",
	},
	{
		abcde: "Sample Abcde 22",
		contact: "Sample Contact 22",
		location: "Sample Location 22",
		supplier: "Sample Supplier 22",
	},
	{
		abcde: "Sample Abcde 23",
		contact: "Sample Contact 23",
		location: "Sample Location 23",
		supplier: "Sample Supplier 23",
	},
	{
		abcde: "Sample Abcde 24",
		contact: "Sample Contact 24",
		location: "Sample Location 24",
		supplier: "Sample Supplier 24",
	},
	{
		abcde: "Sample Abcde 25",
		contact: "Sample Contact 25",
		location: "Sample Location 25",
		supplier: "Sample Supplier 25",
	},
	{
		abcde: "Sample Abcde 26",
		contact: "Sample Contact 26",
		location: "Sample Location 26",
		supplier: "Sample Supplier 26",
	},
	{
		abcde: "Sample Abcde 27",
		contact: "Sample Contact 27",
		location: "Sample Location 27",
		supplier: "Sample Supplier 27",
	},
	{
		abcde: "Sample Abcde 28",
		contact: "Sample Contact 28",
		location: "Sample Location 28",
		supplier: "Sample Supplier 28",
	},
	{
		abcde: "Sample Abcde 29",
		contact: "Sample Contact 29",
		location: "Sample Location 29",
		supplier: "Sample Supplier 29",
	},
	{
		abcde: "Sample Abcde 30",
		contact: "Sample Contact 30",
		location: "Sample Location 30",
		supplier: "Sample Supplier 30",
	},
	{
		abcde: "Sample Abcde 31",
		contact: "Sample Contact 31",
		location: "Sample Location 31",
		supplier: "Sample Supplier 31",
	},
	{
		abcde: "Sample Abcde 32",
		contact: "Sample Contact 32",
		location: "Sample Location 32",
		supplier: "Sample Supplier 32",
	},
	{
		abcde: "Sample Abcde 33",
		contact: "Sample Contact 33",
		location: "Sample Location 33",
		supplier: "Sample Supplier 33",
	},
	{
		abcde: "Sample Abcde 34",
		contact: "Sample Contact 34",
		location: "Sample Location 34",
		supplier: "Sample Supplier 34",
	},
	{
		abcde: "Sample Abcde 35",
		contact: "Sample Contact 35",
		location: "Sample Location 35",
		supplier: "Sample Supplier 35",
	},
	{
		abcde: "Sample Abcde 36",
		contact: "Sample Contact 36",
		location: "Sample Location 36",
		supplier: "Sample Supplier 36",
	},
	{
		abcde: "Sample Abcde 37",
		contact: "Sample Contact 37",
		location: "Sample Location 37",
		supplier: "Sample Supplier 37",
	},
	{
		abcde: "Sample Abcde 38",
		contact: "Sample Contact 38",
		location: "Sample Location 38",
		supplier: "Sample Supplier 38",
	},
	{
		abcde: "Sample Abcde 39",
		contact: "Sample Contact 39",
		location: "Sample Location 39",
		supplier: "Sample Supplier 39",
	},
	{
		abcde: "Sample Abcde 40",
		contact: "Sample Contact 40",
		location: "Sample Location 40",
		supplier: "Sample Supplier 40",
	},
	{
		abcde: "Sample Abcde 41",
		contact: "Sample Contact 41",
		location: "Sample Location 41",
		supplier: "Sample Supplier 41",
	},
	{
		abcde: "Sample Abcde 42",
		contact: "Sample Contact 42",
		location: "Sample Location 42",
		supplier: "Sample Supplier 42",
	},
	{
		abcde: "Sample Abcde 44",
		contact: "Sample Contact 44",
		location: "Sample Location 44",
		supplier: "Sample Supplier 44",
	},
	{
		abcde: "Sample Abcde 44",
		contact: "Sample Contact 44",
		location: "Sample Location 44",
		supplier: "Sample Supplier 44",
	},
	{
		abcde: "Sample Abcde 45",
		contact: "Sample Contact 45",
		location: "Sample Location 45",
		supplier: "Sample Supplier 45",
	},
	// Create me 50+ dummy items
];

export const inventoryData: InventoryTypes[] = [
	{
		id: 1,
		city: "Sample City 1",
		depot: "Sample Depot 1",
		price: "$ 14.05",
		productName: "20 STD - CW",
		quantity: "12 PCS",
		state: "USA",
	},
	{
		id: 2,
		city: "Sample City 2",
		depot: "Sample Depot 2",
		price: "$ 19.99",
		productName: "30 STD - CW",
		quantity: "8 PCS",
		state: "USA",
	},
	{
		id: 3,
		city: "Sample City 3",
		depot: "Sample Depot 3",
		price: "$ 9.99",
		productName: "40 STD - CW",
		quantity: "15 PCS",
		state: "USA",
	},
	{
		id: 4,
		city: "Sample City 4",
		depot: "Sample Depot 4",
		price: "$ 24.50",
		productName: "10 STD - CW",
		quantity: "20 PCS",
		state: "USA",
	},
	{
		id: 5,
		city: "Sample City 5",
		depot: "Sample Depot 5",
		price: "$ 12.75",
		productName: "25 STD - CW",
		quantity: "10 PCS",
		state: "USA",
	},
	{
		id: 6,
		city: "Sample City 6",
		depot: "Sample Depot 6",
		price: "$ 18.99",
		productName: "35 STD - CW",
		quantity: "14 PCS",
		state: "USA",
	},
	{
		id: 7,
		city: "Sample City 7",
		depot: "Sample Depot 7",
		price: "$ 14.95",
		productName: "15 STD - CW",
		quantity: "18 PCS",
		state: "USA",
	},
	{
		id: 8,
		city: "Sample City 8",
		depot: "Sample Depot 8",
		price: "$ 22.50",
		productName: "22 STD - CW",
		quantity: "9 PCS",
		state: "USA",
	},
	{
		id: 9,
		city: "Sample City 9",
		depot: "Sample Depot 9",
		price: "$ 7.99",
		productName: "42 STD - CW",
		quantity: "11 PCS",
		state: "USA",
	},
	{
		id: 10,
		city: "Sample City 10",
		depot: "Sample Depot 10",
		price: "$ 15.25",
		productName: "18 STD - CW",
		quantity: "16 PCS",
		state: "USA",
	},
	{
		id: 11,
		city: "Sample City 11",
		depot: "Sample Depot 11",
		price: "$ 21.99",
		productName: "28 STD - CW",
		quantity: "7 PCS",
		state: "USA",
	},
	{
		id: 12,
		city: "Sample City 12",
		depot: "Sample Depot 12",
		price: "$ 11.50",
		productName: "38 STD - CW",
		quantity: "13 PCS",
		state: "USA",
	},
	{
		id: 13,
		city: "Sample City 13",
		depot: "Sample Depot 13",
		price: "$ 16.75",
		productName: "12 STD - CW",
		quantity: "22 PCS",
		state: "USA",
	},
	{
		id: 14,
		city: "Sample City 14",
		depot: "Sample Depot 14",
		price: "$ 10.99",
		productName: "32 STD - CW",
		quantity: "6 PCS",
		state: "USA",
	},
	{
		id: 15,
		city: "Sample City 15",
		depot: "Sample Depot 15",
		price: "$ 19.25",
		productName: "16 STD - CW",
		quantity: "19 PCS",
		state: "USA",
	},
	// Add more items as needed
];
